### ISSUE TITLE
ImportError: No module named 'fluxclient.utils._utils' when trying to use this module

### ISSUE THREAD

**Issue by davglass** [flux3dp/fluxghost#49]
I've followed all the steps, I have `fluxclient` working as expected. However, when I try to use this module I get the following error:

```
root@3242aa6f0b2d:/usr/local/src/flux/ghost# python3 ./ghost.py --ip 0.0.0.0 --port 3000 -d
fluxghost: 0.6.2, fluxclient: 1.0b2
[2016-10-07 13:24:25,INFO,HTTPServer] Listen HTTP on 0.0.0.0:3000
[2016-10-07 13:24:27,ERROR,HTTP] Unhandle Error
Traceback (most recent call last):
  File "/usr/local/src/flux/ghost/fluxghost/http_handler.py", line 19, in __init__
    BaseHTTPRequestHandler.__init__(self, request, client, server)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/local/src/flux/ghost/fluxghost/http_handler.py", line 42, in do_GET
    klass, kwargs = get_match_ws_service(self.path[4:])
  File "/usr/local/src/flux/ghost/fluxghost/http_websocket_route.py", line 47, in get_match_ws_service
    module_instance = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/src/flux/ghost/fluxghost/websocket/control.py", line 2, in <module>
    from fluxghost.api.control import control_api_mixin
  File "/usr/local/src/flux/ghost/fluxghost/api/control.py", line 11, in <module>
    from fluxclient.fcode.g_to_f import GcodeToFcode
  File "/usr/local/src/flux/client/fluxclient/fcode/g_to_f.py", line 13, in <module>
    from fluxclient.fcode.fcode_base import FcodeBase, POINT_TYPE
  File "/usr/local/src/flux/client/fluxclient/fcode/fcode_base.py", line 8, in <module>
    from fluxclient.utils._utils import Tools
ImportError: No module named 'fluxclient.utils._utils'
```

**Comment by yagami-cerberus** [comment]
Hello, it seems like your `fluxclient` is not installed correctly. Please post your fluxclient install output, maybe that is the problem.

**Comment by davglass** [comment]
Here's the output of `python3 ./setup.py develop`

https://gist.github.com/davglass/d03c3c052c00a1e1c675c15769416437

**Comment by yagami-cerberus** [comment]
The `fluxclient.utils._utils` module is written in C and seems to be skipped by install script. So maybe you have to run `python3 ./setup.py clean` to clean previous compiler result and run `python3 ./setup.py develop` again to get more informations.

**Comment by davglass** [comment]
Here's the output of running `clean`, then `develop` then starting the server and trying to connect to it:

https://gist.github.com/davglass/e9fb28057a6811b1ad9fd450e7effb0f

**Comment by davglass** [comment]
Ok, I finally figured this out and got it to work. If the `libpcl-dev` library isn't installed (on Ubuntu) this error is thrown. Once I installed that this works. Now to get this to connect without discovery :)

**Comment by yagami-cerberus** [comment]
In fact, fluxclient can install and work without libpcl if you are not going to use feature like 3D scanning. There was a bug in install script and we fixed it merged into fluxclient master branch. `fluxclient.utils._utils` module should always be compiled event libpcl is not exist.

libpcl and its depend libraries are really FAT so you can consider to remove them if you like.
